# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommandsTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem

styleSheet = """
QTableWidget {
    background-color: rgb(73, 75, 73);
    alternate-background-color: rgb(112, 112, 112);
    color: white;
}

QHeaderView:section { 
    background-color: cornflowerblue 
}

"""


class CommandsTable(QTableWidget):
    def __init__(self, commands: dict = None):
        super().__init__()
        if commands is None:
            raise ValueError("You're supposed to pass in a list of dicts my guy")
        self.setStyleSheet(styleSheet)
        self.setRowCount(1)
        self.setColumnCount(len(commands['top'].keys()))

        self.columnIndices = {}
        index = 0
        for col in list(commands['top'].keys()):
            self.setHorizontalHeaderItem(index, QTableWidgetItem(col))

            self.columnIndices[col] = index
            index += 1

        for col in list(commands.keys()):
            self.addItem(commands[col])

    def addItem(self, cmd: dict):
        for col in cmd.keys():
            self.setItem(self.rowCount() - 1, self.columnIndices[col], QTableWidgetItem(str(cmd[col])))
        self.insertRow(self.rowCount())

#     def setupUi(self, CommandsTable):
#         CommandsTable.setObjectName("CommandsTable")
#         CommandsTable.resize(738, 608)
#         self.tableWidget = QtWidgets.QTableWidget(CommandsTable)
#         self.tableWidget.setGeometry(QtCore.QRect(0, 0, 741, 601))
#         self.tableWidget.setStyleSheet("background-color: rgb(73, 75, 73);\n"
# "alternate-background-color: rgb(112, 112, 112);")
#         self.tableWidget.setAlternatingRowColors(True)
#         self.tableWidget.setRowCount(10)
#         self.tableWidget.setColumnCount(6)
#         self.tableWidget.setObjectName("tableWidget")
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setHorizontalHeaderItem(0, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setHorizontalHeaderItem(1, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setHorizontalHeaderItem(2, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setHorizontalHeaderItem(3, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setHorizontalHeaderItem(4, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setHorizontalHeaderItem(5, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setItem(0, 0, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setItem(0, 1, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setItem(0, 2, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setItem(0, 3, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setItem(0, 4, item)
#         item = QtWidgets.QTableWidgetItem()
#         self.tableWidget.setItem(0, 5, item)
#
#         self.retranslateUi(CommandsTable)
#         QtCore.QMetaObject.connectSlotsByName(CommandsTable)
#
#     def retranslateUi(self, CommandsTable):
#         _translate = QtCore.QCoreApplication.translate
#         CommandsTable.setWindowTitle(_translate("CommandsTable", "Form"))
#         self.tableWidget.setSortingEnabled(True)
#         item = self.tableWidget.horizontalHeaderItem(0)
#         item.setText(_translate("CommandsTable", "Commnad Input"))
#         item = self.tableWidget.horizontalHeaderItem(1)
#         item.setText(_translate("CommandsTable", "Command Tips"))
#         item = self.tableWidget.horizontalHeaderItem(2)
#         item.setText(_translate("CommandsTable", "Description"))
#         item = self.tableWidget.horizontalHeaderItem(3)
#         item.setText(_translate("CommandsTable", "Global Cooldown"))
#         item = self.tableWidget.horizontalHeaderItem(4)
#         item.setText(_translate("CommandsTable", "User Cooldown"))
#         item = self.tableWidget.horizontalHeaderItem(5)
#         item.setText(_translate("CommandsTable", "Output(s)"))
#         __sortingEnabled = self.tableWidget.isSortingEnabled()
#         self.tableWidget.setSortingEnabled(False)
#         item = self.tableWidget.item(0, 0)
#         item.setText(_translate("CommandsTable", "top"))
#         item = self.tableWidget.item(0, 1)
#         item.setText(_translate("CommandsTable", "[!top, !top {amout}]"))
#         item = self.tableWidget.item(0, 2)
#         item.setText(_translate("CommandsTable", "View the top {amount} users who have the most currency. Default for {amount} is 5, unless a valid number between 1-10 is specified."))
#         item = self.tableWidget.item(0, 3)
#         item.setText(_translate("CommandsTable", "5"))
#         item = self.tableWidget.item(0, 4)
#         item.setText(_translate("CommandsTable", "10"))
#         item = self.tableWidget.item(0, 5)
#         item.setText(_translate("CommandsTable", "[[self.bot.db.getLeaderboard()],[\"Chill... someone just called this command. Read it, I\'ll say the same thing\"],[\"Bro, you got somewhere to be? Wait like ${diff} seconds then try again.\"]]"))
#         self.tableWidget.setSortingEnabled(__sortingEnabled)
